#pragma once

#define VENDOR_ID 0x1B4F // "MS"
#define PRODUCT_ID 0x9206 // "AS"
#define DEVICE_VER 0x0001
#define MANUFACTURER "Stasis"
#define PRODUCT "Stasis Macropad"

#define MATRIX_ROWS 1
#define MATRIX_COLS 8

#define DIRECT_PINS { \
    { D3, D4, C6, D7, B4, B5, B6, B7 } \
}

#define DIODE_DIRECTION COL2ROW

#define DEBOUNCE 5

#define ENCODER_RESOLUTION 4

#define RGB_DI_PIN D2
#define RGBLIGHT_LED_COUNT 6
#define RGBLIGHT_LIMIT_VAL 150
#define RGBLIGHT_DEFAULT_VAL 80
#define RGBLIGHT_HUE_STEP 8
#define RGBLIGHT_SAT_STEP 8
#define RGBLIGHT_VAL_STEP 8
#define RGBLIGHT_SLEEP
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_STATIC_LIGHT

#define OLED_DISPLAY_128X64
#define OLED_BRIGHTNESS 128
#define OLED_TIMEOUT 0
#define OLED_SCROLL_TIMEOUT 0
#define I2C1_CLOCK_SPEED 400000

#define LAYER_SYSTEM 0
#define LAYER_MEDIA 1
#define LAYER_VIRTUALDJ 2

#define OLED_ENCODER_FEEDBACK_TIMEOUT 2000

#define TAPPING_TERM 200

#define MOUSEKEY_DELAY 0
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_WHEEL_DELAY 0
#define MOUSEKEY_WHEEL_INTERVAL 80
#define MOUSEKEY_WHEEL_MAX_SPEED 8
